name: Cordova Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Versión actualizada
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install Cordova
      run: npm install -g cordova
      
    - name: Install project dependencies
      run: npm install
      
    - name: Add Android platform
      run: cordova platform add android@11.0.0
      
    - name: Build Android
      run: cordova build android
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: |
          platforms/android/app/build/outputs/apk/debug/*.apk
          platforms/android/app/build/outputs/bundle/debug/*.aab
        retention-days: 5