name: Cordova Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install Cordova
      run: npm install -g cordova
    - name: Build APK
      run: |
        cordova platform add android
        cordova build android --release
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: platforms/android/app/build/outputs/apk/release/*.apk